site_name: YUBUS
site_description: Sistema para empresas de transporte de pasajeros de pequeña escala (interprovincial, interdistrital).
site_author: PUYU PE
repo_url: https://github.com/puyu-pe/yubus-doc
repo_name: yubus-doc
edit_uri: edit/develop/docs/

nav:
  - Home: index.md
  - Parámetros:
      - Series: parameters/series.md
      - Documentos de identidad: parameters/identity_documents.md
      - Clientes naturales: parameters/natural_clients.md
      - Clientes jurídicos: parameters/legal_clients.md
      - Conductores: parameters/drivers.md
      - Buses: parameters/buses.md
      - Tipos de encomienda: parameters/type_commend.md
      - Rutas y tarifas: parameters/routes_fares.md
      - Medios de pago: parameters/payment_methods.md
      - Conceptos por partida: parameters/departure_concept.md
  - Procesos:
      - Viajes:
          - Crear nuevo viaje: trips/create_trip.md
          - Viajes programados: trips/scheduled_trips.md
          - Registrar salida: trips/register_departure.md
          - Registrar llegada: trips/register_arrival.md
          - Manifiesto de pasajeros: trips/passenger_manifest.md
      - Encomiendas:
          - Asignación de encomiendas: packages/assignment_packages.md
          - Registrar encomienda: packages/register_package.md
          - Salida y entrega de encomiendas: packages/departure_delivery_packages.md
      - Pasajes:
          - Vender pasajes: tickets/sell_ticket.md
  - Reportes:
      - Operaciones: reports/operation.md
      - Consolidado: reports/consolidated.md
      - Comisión por partida: reports/commision.md
      - Notas de crédito: reports/credit_note.md
      - Estado de comprobantes: reports/status_receipt.md

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.shortcuts
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.code.copy

extra:
  shortcuts:
    help: 191      # ?
    next: 78       # n
    previous: 80   # p
    search: 83     # s
